## General ##
type: Deployment # or StatefulSet

## Deployment and Statefulset ##
nameOverride: ""
fullnameOverride: ""
replicaCount: 1

image:
  repository: aiellosti/busca-produtos-api
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

livenessProbe: {}
  # httpGet:
  #   path: "/q/health/live"
  #   port: http
  # initialDelaySeconds: 10
  # periodSeconds: 5
  # timeoutSeconds: 1
  # successThreshold: 1
  # failureThreshold: 3

readinessProbe: {}
  # httpGet:
  #   path: "/q/health/ready"
  #   port: http
  # initialDelaySeconds: 10
  # periodSeconds: 5
  # timeoutSeconds: 1
  # successThreshold: 1
  # failureThreshold: 3

resources: {}
  # limits:
  #   cpu: 250m
  #   memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: nodegroup
  #         operator: In
  #         values:
  #           - apps

volumeMounts: []
  # - name: www
  #   mountPath: /usr/share/nginx/html

volumeClaimTemplates: []
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: "my-storage-class"
  #     resources:
  #       requests:
  #         storage: 1Gi

## Configmap ##
configmap:
  enabled: true
  data:
    api_search: https://api.mercadolibre.com/sites/MLB

## Secret ##
secret:
  enabled: false
  data: {}

## HPA ##
autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 10
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

## Service ##
service:
  type: ClusterIP
  port: 80
  targetPort: http

## Ingress ##
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: example.localhost
      paths: []
        # - path: "/"
        #   pathType: ImplementationSpecific
  tls: []
  #  - secretName: example.localhost-tls
  #    hosts:
  #      - example.localhost
