{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "example.fullname" . }}
  labels:
    {{- include "example.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.data }}
    {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
